// Generated by CoffeeScript 1.6.3
/*
(c) 2011 Jan Monschke
v1.0.1
GeoMock is licensed under the MIT license.
*/


(function() {
  (function() {
    if (typeof navigator === "undefined" || navigator === null) {
      window.navigator = {};
    }
    if (navigator.geolocation == null) {
      window.navigator.geolocation = {};
    }
    navigator.geolocation.delay = 5000;
    navigator.geolocation.shouldFail = false;
    navigator.geolocation.failsAt = -1;
    navigator.geolocation.errorMessage = "There was an error retrieving the position!";
    navigator.geolocation.currentTimeout = -1;
    navigator.geolocation.lastPosReturned = 0;
    navigator.geolocation._sanitizeLastReturned = function() {
      if (this.lastPosReturned > this.waypoints.length - 1) {
        //return this.lastPosReturned = (this.waypoints.length - 1);
        return this.lastPosReturned = 0;
      }
    };
    navigator.geolocation._geoCall = function(method, success, error) {
      var _this = this;
      if (this.shouldFail && (error != null)) {
        return this.currentTimeout = window[method].call(null, function() {
          return error(_this.errorMessage);
        }, this.delay);
      } else {
        if (success != null) {
          return this.currentTimeout = window[method].call(null, function() {
            success(_this.waypoints[_this.lastPosReturned++]);
            return _this._sanitizeLastReturned();
          }, this.delay);
        }
      }
    };
    navigator.geolocation.getCurrentPosition = function(success, error) {
      return this._geoCall("setTimeout", success, error);
    };
    navigator.geolocation.watchPosition = function(success, error) {
      this._geoCall("setInterval", success, error);
      return this.currentTimeout;
    };
    navigator.geolocation.clearWatch = function(id) {
      return clearInterval(id);
    };
    return navigator.geolocation.waypoints = [
      //myLocation Via Zamboni 12: 
      //latitude:  44,495135, 
      //longitude: 11,347575
      {
        coords: {
          //Torre Asinelli
          latitude: 44.494251, 
          longitude: 11.346566,
          accuracy: 1
        }
      }, {
        coords: {
          //San Luca
          latitude: 44.479114, 
          longitude: 11.297597,
          accuracy: 1
        }
      }, {
        coords: {
          //Basilica di San Petronio
          latitude: 44.493395, 
          longitude: 11.343128,
          accuracy: 1
        }
      }, {
        coords: {
          //Medica Palace
          latitude: 44.495775, 
          longitude: 11.340572,
          accuracy: 1
        }  
      }, {
        coords: {
          //Palazzo Re Enzo
          latitude: 44.494401, 
          longitude: 11.342880,
          accuracy: 1
        }
      }, {
        coords: {
          //Palazzo Fava
          latitude: 44.496499, 
          longitude: 11.342296,
          accuracy: 1
        }
      }
    ];
  })();

}).call(this);